DISPLAY_INTERVAL = 10
SCREEN_INTERVAL = 2
ALERT_INTERVAL = 120
THRESHOLD = 10
TOP_SECTIONS = 5
# LOG ORDER IS NOT GUARANTEED, EXPECTED DELAY IN SECONDS
LOG_DELAY = 5

#
# DISPLAY_INTERVAL = 10
# SCREEN_INTERVAL = 2
# ALERT_INTERVAL = 120
# THRESHOLD = 2
# TOP_SECTIONS = 5
# # LOG ORDER IS NOT GUARANTEED, EXPECTED DELAY IN SECONDS
# LOG_DELAY = 10
